"""Astro workspace scaffolding."""
import asyncio
import uuid
from pathlib import Path

from workers.celery_app import celery_app
from workers.event_bus import publish
from config import settings


@celery_app.task(name="workers.workspace.init_workspace")
def init_workspace(project_id: str):
    asyncio.run(_init_workspace(project_id))


async def _init_workspace(project_id: str) -> None:
    workspace = Path(settings.workspace_base_path) / f"project-{project_id}" / "astro-site"

    if workspace.exists():
        return  # Already initialized

    # Directory structure
    for subdir in [
        "src/pages/api",
        "src/components",
        "src/layouts",
        "src/styles",
        "public",
    ]:
        (workspace / subdir).mkdir(parents=True, exist_ok=True)

    # Minimal valid Astro config
    _write(workspace / "astro.config.mjs", """\
import { defineConfig } from 'astro/config';
import tailwind from '@astrojs/tailwind';

export default defineConfig({
  integrations: [tailwind()],
});
""")

    _write(workspace / "tailwind.config.mjs", """\
/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: { extend: {} },
  plugins: [],
};
""")

    _write(workspace / "tsconfig.json", """\
{
  "extends": "astro/tsconfigs/strict",
  "compilerOptions": {
    "baseUrl": ".",
    "paths": { "@/*": ["src/*"] }
  }
}
""")

    _write(workspace / "package.json", """\
{
  "name": "astro-site",
  "type": "module",
  "version": "0.0.1",
  "scripts": {
    "dev": "astro dev",
    "build": "astro build",
    "preview": "astro preview",
    "check": "astro check"
  },
  "dependencies": {
    "astro": "^4.11.0",
    "@astrojs/tailwind": "^5.1.0",
    "tailwindcss": "^3.4.0"
  },
  "devDependencies": {
    "typescript": "^5.4.0"
  }
}
""")

    _write(workspace / "src/styles/global.css", """\
@tailwind base;
@tailwind components;
@tailwind utilities;
""")

    _write(workspace / "src/layouts/MainLayout.astro", """\
---
interface Props {
  title?: string;
}
const { title = 'Site' } = Astro.props;
---
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
    <title>{title}</title>
    <slot name="head" />
  </head>
  <body class="min-h-screen bg-white text-gray-900 antialiased">
    <slot />
  </body>
</html>
""")

    _write(workspace / "src/pages/index.astro", """\
---
// Homepage — generated by Frontend Agent
---
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width" />
    <title>Home</title>
  </head>
  <body>
    <h1>Welcome</h1>
    <p>This page will be built by the Frontend Agent.</p>
  </body>
</html>
""")

    _write(workspace / ".env.example", """\
# Environment variables required by this project
# Copy to .env and fill in values
""")

    _write(workspace / ".gitignore", """\
dist/
node_modules/
.env
.astro/
""")

    publish("workspace.initialized", {"project_id": project_id, "path": str(workspace)})


def _write(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8")
